articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

# URL 설정을 app 단위로!
urlpatterns = [
    # http://127.0.0.1:8000/articles/
    path('', views.index, name='index'),
    # http://127.0.0.1:8000/articles/new
    # ModelForm -> create와 new의 기능을 create에 합쳐서 더이상 필요없어졌음
    #path('new/', views.new, name='new'),
    # http://127.0.0.1:8000/articles/create/
    path('create/', views.create, name='create'),
    # http://127.0.0.1:8000/articles/1/ : 1번글
    # http://127.0.0.1:8000/articles/3/ : 3번글
    path('<int:pk>/', views.detail, name='detail'),

    # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
    # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
    path('<int:pk>/update/', views.update, name='update'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
'''
게시판 기능
- 제목(20글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/ 시간)
'''

# 1. 모델 설계(DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):

    class Meta:
        # Aricle에 있는 것을 모델로 해서
        model = Article
        # 모든 것들을 필드로 불러온다.
        fields = '__all__'
        # 만약 타이들만 하고 싶다면 fields = ['title']
        # 만약 타이들과 컨텐츠를 하고 싶다면 fields = ['title', 'content']

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm # ModelForm을 사용하기 위한 코드 추가

# Create your views here.

# 요청 정보를 받아서
def index(request):
    # 게시글을 가져와서
    # articles = Article.objects.all()
    articles = Article.objects.order_by('-pk')
    
    # Template에 전달한다.
    context = {
        'articles': articles
    }

    # 페이지를 render
    return render(request,'articles/index.html', context)

# 63번째 # !def new 함수 주석 처리! 
# index.html, urls에서 new 없애기!
# def new(request):
#      # ModelForm용 추가 코드
#     article_form = ArticleForm()
#     context = {
#         'article_form': article_form
#     }
#     #return render(request, 'articles/new.html')
#     return render(request, 'articles/new.html', context=context)


''' New + Create 합치기 전 코드
def create(request):
    # DB에 저장하는 로직
    # GET을 사용할 때 받는 방법
    ### ModelForm 사용 전
    # title = request.GET.get('title')
    # content = request.GET.get('content')

    # POST를 사용할 때는 POST.get으로 바꿔줘야 함!
    title = request.POST.get('title')
    content = request.POST.get('content')

    # Models.py에서 생성한 DB(Article)에 저장하기
    # DB를 사용하기 위해 위쪽에 Article을 import 해오기
    Article.objects.create(title=title, content=content)
    ### ModelFrom 사용전 끝
    article_form = ArticleForm(request.POST)

    # 유효성 검사
    if article_form.is_valid():
        article_form.save()
        return redirect('articles:index')
    else:
        #print('유효하지 않습니다.')
        # 유효하지 않을 때 무엇을 하면 좋을까?
        # form 페이지에 메시지를 띄워서 사용자에게 보여주기!
        # new 함수에 있는 내용을 붙여넣기
        context = {
            'article_form': article_form
        }
        #return render(request, 'articles/new.html')
        return render(request, 'articles/new.html', context=context)
'''

# new 함수와 create 함수가 같아보이기 때문에 합친다!
# !def new 함수 주석 처리!

def create(request):
    # method가 POST인 경우
    if request.method == 'POST':
        # DB에 저장하는 로직
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:index')
    # method가 GET인 경우
    else:
        article_form = ArticleForm()
    # invalid일 경우 74번째에서 아랫줄로 바로 내려감. 들여쓰기 주의!    
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/new.html', context=context)

def detail(request, pk):
    # 특정 글을 가져온다.
    article = Article.objects.get(pk=pk)
    # template에 객체 전달
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        # POST : input 값 가져와서, 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, instance=article) # 인스턴스를 주지않으면 생성이 됨
        # 유효성 검사 통과하면 상세보기 페이지로
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:detail', article.pk)
        # 유효성 검사 통과 못하면 => context부터 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)

    context = {
        'article_form' : article_form
    }
    return render(request, 'articles/update.html', context)


    # Update와 Create에서 instance만 달라진다!

articles/templates/articles/detail.html
<h1> {{ article.pk }}번 게시글 </h1>
<p> {{ article.created_at }} | {{ article.updated_at }} </p>
<p> {{ article.content }} </p>
<a href="{% url 'articles:update' article.pk %}">수정하기</a>

articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1> 게시판 </h1>
  <!-- 원래 있던 articles:new는 create와 new를 합치면서 삭제함-->
  <a href="{% url 'articles:create' %}"> 글 쓰기 </a>

  {% for article in articles %}
  <h3><a href="{% url 'articles:detail' article.pk %}"> {{ article.title }} </a></h3>
  <p> {{ article.created_at }} | {{ article.updated_at }} </p>
  <hr>
  {% endfor %}

</body>

</html>

articles/templates/articles/new.html
<h1> 글쓰기 </h1>

<!-- form : 사용자에게 양식을 제공하고
  값을 받아서(input : name, value)
  서버에 전송(form : action, )-->

<!-- 
  1. <form action="/articles/create/"> 로 
  작성해도 가능하지만, url이 변하거나 path 구성이 변하면
  하나씩 찾아가서 바꿔야 하기때문에 아래와 같이 선언
-->

<!-- 
  2. <form action="{% url 'articles:create' %}"> 
  GET : 어떤 리소스의 표현, 데이터를 조회하는 데 사용
  POST : 서버에 상태나 변화를 일으킴. 어떤 리소스(Article)의 entity를 제출함.
  여기서는 Article에 값을 반영하므로, 전송을 하는 폼의 method="POST"를 이용
-->
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <!-- ModelForm 확인용 .as_p는 p태그로 감싸줌 -->
  {{ article_form.as_p }}

  <!--
  <label for="title">제목 : </label>
  <input type="text" name="title" id="title" required>
  <label for="content">내용 : </label>
  <textarea name="content" id="content" cols="30" rows="10" required></textarea> -->
  <input type="submit" value="글쓰기">
</form>

articles/templates/articles/update.html
<h1> 글 수정하기 </h1>

<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <input type="submit" value="수정">
</form>